disable_motion_planning: false
approach_planner:

  planning_groups: # Sorted by order of preference
    - full_body

  joint_tolerance: 0.01
  skip_planning_approach_vel: 0.5
skip_planning_approach_min_dur: 0.5
