
 joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

 full_body_controller:
   type: "position_controllers/JointTrajectoryController"
   joints:
     - Rarm
     - Larm
     - RHip
     - LHip
     - Head
     - Neck

   gains:
     Rarm: {p: 1,  d: 0, i: 0, i_clamp: 0}
     Larm: {p: 1,  d: 0, i: 0, i_clamp: 0}
     RHip: {p: 1,  d: 0, i: 0, i_clamp: 0}
     LHip: {p: 1,  d: 0, i: 0, i_clamp: 0}
     Head: {p: 1,  d: 0, i: 0, i_clamp: 0}
     Neck: {p: 1,  d: 0, i: 0, i_clamp: 0}

   constraints:
     goal_time: &goal_time_constraint 0.6
     stopped_velocity_tolerance: &stopped_velocity_constraint 5.0 # FIXME: See #8429
     Rarm:
       goal: &goal_pos_constraint 0.0005
     Larm:
       goal: *goal_pos_constraint
     RHip:
       goal: *goal_pos_constraint
     LHip:
       goal: *goal_pos_constraint
     Head:
       goal: *goal_pos_constraint
     Neck:
       goal: *goal_pos_constraint

   state_publish_rate:  50            # Override default
   action_monitor_rate: 50            # Override default
   stop_trajectory_duration: 0   


#Setting gazebo PID to call POSITION_PID instead of POSITION and fix gravity issue
 gazebo_ros_control:   
   pid_gains:
     Rarm: {p: 1,  d: 0, i: 0, i_clamp: 0}
     Larm: {p: 1,  d: 0, i: 0, i_clamp: 0}
     RHip: {p: 1,  d: 0, i: 0, i_clamp: 0}
     LHip: {p: 1,  d: 0, i: 0, i_clamp: 0}
     Head: {p: 1,  d: 0, i: 0, i_clamp: 0}
     Neck: {p: 1,  d: 0, i: 0, i_clamp: 0}
