#!/usr/bin/env python
# license removed for brevity
import rospy
from dynamic_graph_bridge_msgs.msg import Vector
from sensor_msgs.msg import JointState
import sys

if len(sys.argv)>1:
    input_topic = sys.argv[1]
    if len(sys.argv)>2:
        output_topic = sys.argv[2]
    else:
        output_topic = "/sot/joint_state"
else:
    input_topic = "/sot_hpp/state"

rospy.init_node('sot_reemitter', anonymous=True)
pub = rospy.Publisher(output_topic, JointState, queue_size=10)
    
seqnb = 0
aJS = JointState()

jointnames =  rospy.get_param("/sot_controller/joint_names")
    
def jointreceived(jstates):
    global seqnb
    seqnb = seqnb+1
    aJS.header.seq = seqnb
    aJS.header.stamp = rospy.Time.now()
    aJS.header.frame_id = "base_link"
    aJS.name = jointnames
    aJS.position = jstates.data[6:]
    aJS.velocity = []
    aJS.effort = []
    pub.publish(aJS)

def listener():
    rospy.Subscriber(input_topic, Vector, jointreceived)
    rospy.spin()
    
if __name__ == '__main__':
    try:
        listener()
    except rospy.ROSInterruptException:
        pass
