yoyoman01:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  Head_position_controller:
    type: effort_controllers/JointPositionController
    joint: Head
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Neck_position_controller:
    type: effort_controllers/JointPositionController
    joint: Neck
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rarm_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rarm
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Larm_position_controller:
    type: effort_controllers/JointPositionController
    joint: Larm
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RHip_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHip
    pid: {p: 100.0, i: 0.01, d: 10.0}
  LHip_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHip
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
