
#robot_description:
  gains:
   # Position Controllers ---------------------------------------
    Head: {p: 100.0, i: 0.01, d: 10.0}
    Neck: {p: 100.0, i: 0.01, d: 10.0}
    Rarm: {p: 100.0, i: 0.01, d: 10.0}
    Larm: {p: 100.0, i: 0.01, d: 10.0}
    RHip: {p: 100.0, i: 0.01, d: 10.0}
    LHip: {p: 100.0, i: 0.01, d: 10.0}
